# Default initial positions for the panda arm's ros2_control fake system
initial_positions:
  joint_a1: 0.0698132
  joint_a2: 0.523599
  joint_a3: 0.06056293
  joint_a4: -1.39626
  joint_a5: 0.0863938
  joint_a6: 0.593412
  joint_a7: -0.0174533
#  joint_a1: -1.5707
#  joint_a2: -0.7854
#  joint_a3: 0.0
#  joint_a4: 1.3962
#  joint_a5: 0.0
#  joint_a6: 0.6109
#  joint_a7: 0.0